EMAIL_SUBJECT_TEMPLATE = "Senior Software Engineer | Backend, Distributed Systems, AI/LLM"

EMAIL_BODY_TEMPLATE = """\
Hello Hiring Manager/Team,

I hope you're having a great week!

I'm reaching out to express my strong interest in Software Engineering opportunities within your team.

I’m a Senior Software Engineer with 7+ years of experience building scalable backend systems, distributed architectures, and AI-driven automation solutions. I’ve worked extensively on high-throughput systems in the air cargo and fintech domains, including leading the transition to IATA ONE Record (API-based global standard) and building LLM-based automation pipelines.

My career highlights include:
- AI & LLM Systems: Engineered an AI-powered Cargo mapping automation pipeline using LLM-based agents and MCP servers, slashing manual effort by 70%.
- Distributed Systems on AWS: Delivered high-throughput event-driven microservices processing 10K+ daily shipments with 99%+ reliability.
- Advanced Database Engineering: Extensive experience with PostgreSQL, MongoDB, and Redis—optimizing queries, indexing, and performance tuning for systems serving 2K+ reqs/min.
- Tech Stack Expertise: Python, C#, .NET Core, Node.js, and comprehensive AWS Cloud infrastructure.


For more details about my professional journey, please find my links below, and my detailed resume attached.

LinkedIn: https://www.linkedin.com/in/souravaggarwal/
GitHub: https://github.com/SouravAggarwal
Resume (Google Drive): https://drive.google.com/file/d/1Z6FkKKnGqp7tzNd4wVWzB4VjmBVpnU1N/view?usp=sharing

Looking forward to the possibility of collaborating.

Best regards,
Sourav Aggarwal

(Note: This email is generated by AI, please ignore if irrelevant.)
"""

EMAIL_HTML_TEMPLATE = """\
<!DOCTYPE html>
<html>
<head>
<style>
    body {{
        font-family: 'Inter', 'Segoe UI', Arial, sans-serif;
        line-height: 1.6;
        color: #333333;
        margin: 0;
        padding: 0;
    }}
    .container {{
        max-width: 1000px;
        margin: 0 auto;
        padding: 20px;
        background-color: #ffffff;
    }}
    .header {{
        background: linear-gradient(135deg, #1e3c72 0%, #2a5298 100%);
        color: #ffffff;
        padding: 30px 20px;
        text-align: center;
        border-radius: 8px 8px 0 0;
    }}
    .header h1 {{
        margin: 0;
        font-size: 24px;
        font-weight: 600;
        letter-spacing: 0.5px;
    }}
    .header p {{
        margin: 5px 0 0;
        font-size: 16px;
        opacity: 0.9;
    }}
    .content {{
        padding: 30px;
        border: 1px solid #e0e0e0;
        border-top: none;
        border-radius: 0 0 8px 8px;
    }}
    .greeting {{
        font-size: 18px;
        font-weight: 600;
        color: #2c3e50;
    }}
    .highlight-box {{
        background-color: #f8f9fa;
        border-left: 4px solid #2a5298;
        padding: 15px 20px;
        margin: 25px 0;
        border-radius: 0 4px 4px 0;
    }}
    .skills-list {{
        padding-left: 20px;
        margin: 15px 0;
    }}
    .skills-list li {{
        margin-bottom: 10px;
    }}
    .skills-list strong {{
        color: #2a5298;
    }}
    .cta-container {{
        text-align: center;
        margin: 35px 0 20px;
    }}
    .button {{
        display: inline-block;
        padding: 12px 24px;
        background-color: #2a5298;
        color: #ffffff !important;
        text-decoration: none;
        border-radius: 5px;
        font-weight: 600;
        margin: 5px;
        transition: background-color 0.3s;
    }}
    .button-outline {{
        display: inline-block;
        padding: 12px 24px;
        background-color: transparent;
        color: #2a5298 !important;
        text-decoration: none;
        border: 2px solid #2a5298;
        border-radius: 5px;
        font-weight: 600;
        margin: 5px;
    }}
    .footer {{
        margin-top: 30px;
        padding-top: 20px;
        border-top: 1px solid #eeeeee;
        text-align: center;
        color: #7f8c8d;
        font-size: 14px;
    }}
    .signature-name {{
        font-size: 18px;
        font-weight: bold;
        color: #2c3e50;
        margin: 5px 0;
    }}
</style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>Sourav Aggarwal</h1>
            <p>Senior Software Engineer | AI & Distributed Systems</p>
        </div>
        
        <div class="content">
            <p class="greeting">Hello {recipient_name},</p>
            
            <p>I hope you're having a great week!</p>
            
            <p>I'm reaching out to express my strong interest in Software Engineering opportunities within your team.</p>
            
            <p>I’m a Senior Software Engineer with <strong>7+ years of experience</strong> building scalable backend systems, distributed architectures, and AI-driven automation solutions. I’ve worked extensively on high-throughput systems in the air cargo and fintech domains, including leading the transition to IATA ONE Record (API-based global standard) and building LLM-based automation pipelines.</p>
            
            <p><strong>Key Career Highlights:</strong></p>
            <ul class="skills-list">
                <li><strong>AI & LLM Systems:</strong> Engineered an AI-powered automation pipeline using LLM-based agents and MCP servers, slashing manual mapping effort by 70%.</li>
                <li><strong>Distributed Core Systems:</strong> Delivered high-throughput, event-driven architectures processing 10K+ daily shipments with 99%+ reliability.</li>
                <li><strong>Performance Tuning:</strong> Deep expertise in optimizing Database architectures (PostgreSQL, MongoDB, Redis) to reliably serve over 2K requests/minute.</li>
                <li><strong>Technology Stack:</strong> Fluent in Python, C#, .NET Core, Node.js, combined with robust AWS Cloud provisioning.</li>
            </ul>
            

            
            <div class="cta-container">
                <a href="https://drive.google.com/file/d/1Z6FkKKnGqp7tzNd4wVWzB4VjmBVpnU1N/view?usp=sharing" class="button">View Online Resume</a>
                <a href="https://www.linkedin.com/in/souravaggarwal/" class="button-outline">LinkedIn Profile</a>
                <a href="https://github.com/SouravAggarwal" class="button-outline">GitHub Portfolio</a>
            </div>
            
            <p>I have also attached a PDF copy of my resume for your convenience.</p>
            
            <div class="footer">
                <p>Looking forward to hearing from you.</p>
                <div class="signature">
                    <p style="margin-bottom: 2px;">Best regards,</p>
                    <p class="signature-name">Sourav Aggarwal</p>
                    <p style="margin-top: 0; color: #2a5298;">+91-9911019897 | srvaggarwal96@gmail.com</p>
                </div>
                <p style="margin-top: 15px; font-size: 12px; color: #95a5a6; font-style: italic;">Note: This email is generated by AI, please ignore if irrelevant.</p>
            </div>
        </div>
    </div>
</body>
</html>
"""

def get_email_content(recipient_name="Hiring Manager/Team"):
    """
    Generates the subject, plain text body, and html body for the email.
    """
    subject = EMAIL_SUBJECT_TEMPLATE
    plain_text_body = EMAIL_BODY_TEMPLATE.format(recipient_name=recipient_name)
    html_body = EMAIL_HTML_TEMPLATE.format(recipient_name=recipient_name)
    return subject, plain_text_body, html_body

